apiVersion: v1
kind: Pod
metadata:
  name: HomePod
  namespace: mlab2 
  labels:
    app: HomePod
spec:
  nodeName: ai03
  containers:
  - name: HomePod 
    image: gemfield/deepvac:vision-11.0.3-cudnn8-devel-ubuntu20.04-vnc
    imagePullPolicy: IfNotPresent 
    workingDir: /home/gemfield 
    env:
    - name: TZ 
      value: Asia/Shanghai
    - name: HOME
      value: /home/gemfield
    - name: DEEPVAC_USER
      value: gemfield
    resources:
      requests:
        memory: "6Gi"
      limits:
        memory: "18Gi" 
    ports:
    - name: tensorboard
      containerPort: 6006
    - name: vnc
      containerPort: 5900
    - name: novnc
      containerPort: 7030
    volumeMounts:
    - mountPath: /dev/shm
      name: dshm
    - name: home4gemfield
      mountPath: /home/gemfield
  hostNetwork: false
  restartPolicy: Always 
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "2Gi"
  - name: home4gemfield
    persistentVolumeClaim:
       claimName: gemfield
---
apiVersion: v1
kind: Service
metadata:
  name: gemfield-service
  namespace: mlab2
  labels:
    app: HomePod
spec:
  externalIPs:
    - 192.168.0.34
  ports:
    - port: 6006
      targetPort: 6006
      name: tensorboard
    - port: 27030
      targetPort: 7030
      name: novnc
    - port: 5900
      targetPort: 5900
      name: vnc
  selector:
    app: HomePod